### PR TITLE
Create CMake file 

### LINKED ISSUE #65: Create a CMake instead of Make file

### PR DESCRIPTION
**Pull request by 0xGodspeed**
Also update .gitignore to ignore cmake related cache and files, and filter executable. Fixes #65

### CODE REVIEW

**Comment by Himanshu40** [comment]
@0xGodspeed That's rea;;y a great work. Can you add these too?
```cmake
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
```

**Comment by 0xGodspeed** [comment]
@Himanshu40 sure

**Comment by Himanshu40** [comment]
Great work @0xGodspeed but please can you edit something like this which is more readable.

```cmake
cmake_minimum_required(VERSION 3.10)

project(Image-Filter-Application)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_executable(filter
               main.cpp
               src/filters.cpp
               src/helpers.cpp)

add_compile_options(-fsanitize=asigned-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c++11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow)
```

**Comment by 0xGodspeed** [comment]
no need for add_link_options ?

**Comment by chandrakant100** [comment]
everything looks great to me.After merging please update the readme.

**Review by chandrakant100 — APPROVED** [review]

**Pull request merged**
